---
- name: Include kerberos task
  tags: ad_member_samba
  include_tasks: kerberos.yml

- name: Join to the domain
  tags: ad_member_samba
  # do not log to preserve password secrecy
  no_log: True
  shell: "net ads join -k -U {{ ad_member_kerberos_user }}%{{ ad_member_kerberos_pass }} osName={{ ansible_distribution }} osVer={{ ansible_distribution_version }}"
  notify:
    - sssd restart
